import 'dart:convert';
import 'dart:io';
import 'dart:ui' as ui;
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

/// Singleton that stores top-down PNG thumbnails of every furniture GLB.
///
/// Thumbnails are generated by the Three.js viewer the first time a 3D view
/// opens, then saved to disk so they load instantly on every subsequent launch.
///
/// Key convention
/// ──────────────
///   Built-in types  → FurnitureType.name  (e.g. "chair", "sofa")
///   Custom GLBs     → glbFileName          (e.g. "custom_couch_abc123.glb")
class ThumbnailCache extends ChangeNotifier {
  ThumbnailCache._();
  static final instance = ThumbnailCache._();

  // ── In-memory image map ──────────────────────────────────────────────────
  final Map<String, ui.Image> _images = {};
  Map<String, ui.Image> get images => Map.unmodifiable(_images);

  bool hasImage(String key) => _images.containsKey(key);

  // ── Disk paths ───────────────────────────────────────────────────────────
  static Directory get _thumbDir {
    final String base;
    if (Platform.isWindows) {
      base = Platform.environment['APPDATA'] ?? Directory.systemTemp.path;
    } else {
      base = Platform.environment['HOME'] ?? Directory.systemTemp.path;
    }
    return Directory(
      '$base${Platform.pathSeparator}furniture_visualizer'
      '${Platform.pathSeparator}thumbnails',
    );
  }

  static File _thumbFile(String key) {
    // Sanitise key so it is safe as a filename
    final safe = key.replaceAll(RegExp(r'[\\/:*?"<>|]'), '_');
    return File('${_thumbDir.path}${Platform.pathSeparator}$safe.png');
  }

  // ── Load all cached thumbnails from disk (call once at startup) ──────────
  Future<void> loadAll() async {
    final dir = _thumbDir;
    if (!dir.existsSync()) return;
    for (final entity in dir.listSync()) {
      if (entity is File && entity.path.endsWith('.png')) {
        try {
          final bytes = await entity.readAsBytes();
          final img = await _decodeBytes(bytes);
          final key = entity.uri.pathSegments.last.replaceAll('.png', '');
          _images[key] = img;
        } catch (e) {
          debugPrint('[ThumbnailCache] failed to load ${entity.path}: $e');
        }
      }
    }
    if (_images.isNotEmpty) notifyListeners();
  }

  // ── Store a thumbnail received as a base64 data-URL from Three.js ────────
  Future<void> store(String key, String base64DataUrl) async {
    try {
      // Strip the "data:image/png;base64," prefix
      final comma = base64DataUrl.indexOf(',');
      final b64 = comma >= 0
          ? base64DataUrl.substring(comma + 1)
          : base64DataUrl;
      final bytes = base64Decode(b64);

      // Decode to ui.Image for painting
      final img = await _decodeBytes(bytes);
      _images[key] = img;

      // Persist to disk
      final dir = _thumbDir;
      if (!dir.existsSync()) dir.createSync(recursive: true);
      await _thumbFile(key).writeAsBytes(bytes);

      notifyListeners();
    } catch (e) {
      debugPrint('[ThumbnailCache] store error key=$key: $e');
    }
  }

  // ── Helper ───────────────────────────────────────────────────────────────
  static Future<ui.Image> _decodeBytes(Uint8List bytes) async {
    final codec = await ui.instantiateImageCodec(bytes);
    final frame = await codec.getNextFrame();
    return frame.image;
  }
}
